### PR TITLE
Made Cheat-sheet more palatable

### PR DESCRIPTION
**Pull request by N-E-W-T-O-N**

### CODE REVIEW

**Comment by N-E-W-T-O-N** [comment]
Made Python cheatsheet more  palatable.

**Comment by N-E-W-T-O-N** [comment]
Please merge my PR.

**Comment by N-E-W-T-O-N** [comment]
Please give me hacktoberfest acceptance tag

**Comment by Suryansh1720001** [comment]
Hello @N-E-W-T-O-N
Thanks for your contribution.
Let's connect ->
GitHub -> @Suryansh1720001 (Follow)
LinkedIn -> https://www.linkedin.com/in/suryanshprajapati17

**Comment by N-E-W-T-O-N** [comment]
Thank you Suryansh1720001. I still have more things to add in cheatsheet.

**Pull request merged**
